name: CI

on:
  push:

jobs:
  javascript-tests:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: 'src/main/resources/static/js/package-lock.json'

      - name: Install JavaScript dependencies
        working-directory: src/main/resources/static/js
        run: npm ci

      - name: Run JavaScript tests
        working-directory: src/main/resources/static/js
        run: npm run test

  test-extension:
    name: Test Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Test profiler
        run: ./mvnw verify

  test-maven-demos:
    name: Test Maven Demo Projects
    runs-on: ubuntu-latest
    needs: test-extension
    strategy:
      fail-fast: false
      matrix:
        demo:
          - spring-boot-3.4-maven
          - spring-boot-3.5-maven
#          - spring-boot-3.5-maven-failsafe-parallel
#          - spring-boot-3.5-maven-junit-parallel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'demo/${{ matrix.demo }}/pom.xml'

      - name: Install extension to local repository
        run: ./mvnw clean install -DskipTests

      - name: Build demo project
        id: build-demo
        working-directory: demo/${{ matrix.demo }}
        run: ./mvnw verify

      - name: Upload demo test results
        uses: actions/upload-artifact@v4
        if: always() && hashFiles('demo/${{ matrix.demo }}/target/spring-test-profiler/latest.html') != ''
        with:
          name: demo-test-results-${{ matrix.demo }}
          path: demo/${{ matrix.demo }}/target/spring-test-profiler/

  test-gradle-demos:
    name: Test Gradle Demo Projects
    runs-on: ubuntu-latest
    needs: test-extension
    strategy:
      fail-fast: false
      matrix:
        demo:
          - spring-boot-3.5-gradle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: 'demo/${{ matrix.demo }}/build.gradle'

      - name: Install extension to local repository
        run: ./mvnw clean install -DskipTests

      - name: Build demo project
        id: build-demo
        working-directory: demo/${{ matrix.demo }}
        run: ./gradlew build

      - name: Upload demo test results
        uses: actions/upload-artifact@v4
        if: always() && hashFiles('demo/${{ matrix.demo }}/build/spring-test-profiler/latest.html') != ''
        with:
          name: demo-test-results-${{ matrix.demo }}
          path: demo/${{ matrix.demo }}/build/spring-test-profiler/

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [javascript-tests, test-extension, test-maven-demos, test-gradle-demos]
    if: always()

    steps:
      - name: Test Results Summary
        run: |
          echo "## Test Results Summary"
          echo ""
          echo "### JavaScript Tests"
          if [ "${{ needs.javascript-tests.result }}" == "success" ]; then
            echo "✅ JavaScript tests passed"
          else
            echo "❌ JavaScript tests failed"
          fi
          echo ""
          echo "### Extension Tests"
          if [ "${{ needs.test-extension.result }}" == "success" ]; then
            echo "✅ Extension tests passed"
          else
            echo "❌ Extension tests failed"
          fi
          echo ""
          echo "### Demo Projects"
          echo "Maven demos status: ${{ needs.test-maven-demos.result }}"
          echo "Gradle demos status: ${{ needs.test-gradle-demos.result }}"
          echo ""
          echo "Note: Individual demo project results can be found in the workflow run details."

      - name: Check critical failures
        if: needs.javascript-tests.result == 'failure' || needs.test-extension.result == 'failure'
        run: |
          echo "Critical failure: Core tests failed"
          if [ "${{ needs.javascript-tests.result }}" == "failure" ]; then
            echo "JavaScript tests failed"
          fi
          if [ "${{ needs.test-extension.result }}" == "failure" ]; then
            echo "Extension tests failed"
          fi
          exit 1

      - name: Final status
        run: |
          if [ "${{ needs.javascript-tests.result }}" == "success" ] && [ "${{ needs.test-extension.result }}" == "success" ]; then
            echo "✅ Core tests (JavaScript + Extension) passed - build is acceptable"
            echo "Check individual demo results in the matrix job above"
          else
            echo "Build failed due to core test failures"
            exit 1
          fi
